#output_implementation.py

#A module that implements the various outputs.
# Each kind of output that can be generated by the program must be implemented as a separate class


class Distance:
    'Prints the Total Distance of the Trip'
    def __init__(self,obj:dict): -> None:
        self._distance = int(round(obj['route']['distance']))

    def output(self):
        print("TOTAL DISTANCE: {} miles".format(self._distance))
        print()

class Time:
    "Prints the Total Time of the Trip"
    def __init__(self,obj:dict): -> None:
        self._time = int(round(obj['route']['time'])/60)

    def output(self):
        print("TOTAL TIME: {} minutes".format(self._time))
        print()

def Directions:
    "Prints directions for the trip"
    def __init__(self, obj:dict)-> None:
        self._dict_to_print = obj

    def output(self):
        for leg in self._obj["route"]["legs"]:
            for item in (leg["maneuvers"]):
                print(item['narrative'])
        print()

